version: '3.1'

services:

  # web ui for database (http)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # database
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  # api
  dashboard-api:
    image: louisbrunet/dashboard-api
    restart: always
    # ports ? (5174)

  # www 8080
  web:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - /home/ubuntu/wwwdashboard/vue-dashboard/dist:/usr/share/nginx/html:ro
      - /home/ubuntu/wwwdashboard/nginx:/etc/nginx/conf.d:ro
